### ISSUE TITLE
Identify high confidence SNPs across X and Y

### ISSUE THREAD

**Issue by Phillip-a-richmond** [hackseq/2016_project_6#5]
From dbSNP and GIAB gold standard NA12878, identify the high confident SNPs that can be used for allele-ratio queries

**Comment by mathbionerd** [comment]
My concern about using the GIAB gold standard is that we'll then have downstream ascertainment bias by the population of that individual.

**Comment by mathbionerd** [comment]
This will be combined into the variant calling issue ([https://github.com/hackseq/2016_project_6/issues/10](https://github.com/hackseq/2016_project_6/issues/10)), including calling SNPs from the data and inferring read balance.
