### ISSUE TITLE
Create conda environment

### ISSUE THREAD

**Issue by BrunoGrandePhD** [hackseq/2016_project_6#6]

**Comment by thw17** [comment]
I've installed anaconda (Python 2.7) to /hackathon/Hackathon_Project_6.  You can add it to your environment with the command:

`export PATH=/hackathon/Hackathon_Project_6/anaconda2/bin:$PATH`

I've created an environment for the group (Python 2.7) called xyploidy.  If anaconda is loaded in your environment (you can check with the command `which conda`), you can activate this environment with:

`source activate xyploidy`

and deactivate it (once activated) with:

`source deactivate xyploidy`

**Comment by thw17** [comment]
I've added a bunch of programs and packages to the environment xyploidy.  I've listed them below (you can also see them in the file xyploidy_environment.yml in the /hackathon/Hackathon_Project_6 directory).  Let me know if you want anything else installed.

name: xyploidy
channels: !!python/tuple
- !!python/unicode 'conda-forge'
- !!python/unicode 'bioconda'
- !!python/unicode 'r'
- !!python/unicode 'defaults'
  dependencies:
- bioconda::bamtools=2.4.0=3
- bioconda::bcftools=1.3.1=1
- bioconda::bedops=2.4.20=0
- bioconda::bedtools=2.26.0=0
- bioconda::biopython=1.68=py27_0
- bioconda::bwa=0.7.15=0
- bioconda::cyvcf2=0.5.5=py27_0
- bioconda::freebayes=1.0.2.29=py27_2
- bioconda::htslib=1.3.1=1
- bioconda::java-jdk=8.0.92=1
- bioconda::lastz=1.0.2=1
- bioconda::mmtf-python=1.0.2=py27_0
- bioconda::novoalign=3.04.04=3
- bioconda::picard=2.5.0=1
- bioconda::pysam=0.9.1.4=py27_0
- bioconda::pyvcf=0.6.8=py27_0
- bioconda::samtools=1.3.1=4
- conda-forge::ca-certificates=2016.8.31=0
- conda-forge::cairo=1.12.18=8
- conda-forge::certifi=2016.8.31=py27_0
- conda-forge::curl=7.49.1=1
- conda-forge::cycler=0.10.0=py27_0
- conda-forge::fontconfig=2.11.1=3
- conda-forge::freetype=2.6.3=1
- conda-forge::functools32=3.2.3.2=py27_1
- conda-forge::gettext=0.19.7=1
- conda-forge::glib=2.48.0=4
- conda-forge::harfbuzz=1.0.6=0
- conda-forge::icu=56.1=4
- conda-forge::jpeg=9b=0
- conda-forge::libffi=3.2.1=2
- conda-forge::libiconv=1.14=3
- conda-forge::libpng=1.6.24=0
- conda-forge::libtiff=4.0.6=6
- conda-forge::libxml2=2.9.4=2
- conda-forge::matplotlib=1.5.3=np111py27_2
- conda-forge::ncurses=5.9=9
- conda-forge::openssl=1.0.2h=2
- conda-forge::pandas=0.19.0=np111py27_0
- conda-forge::pango=1.40.1=0
- conda-forge::patsy=0.4.1=py27_0
- conda-forge::pcre=8.38=1
- conda-forge::pillow=3.4.1=py27_1
- conda-forge::pip=8.1.2=py27_0
- conda-forge::pixman=0.32.6=0
- conda-forge::pyparsing=2.1.10=py27_0
- conda-forge::pyqt=4.11.4=py27_0
- conda-forge::python=2.7.12=1
- conda-forge::python-dateutil=2.5.3=py27_0
- conda-forge::pytz=2016.7=py27_0
- conda-forge::qt=4.8.7=3
- conda-forge::readline=6.2=0
- conda-forge::seaborn=0.7.1=py27_0
- conda-forge::setuptools=26.1.1=py27_0
- conda-forge::sip=4.18=py27_0
- conda-forge::six=1.10.0=py27_0
- conda-forge::sqlite=3.13.0=1
- conda-forge::statsmodels=0.6.1=np111py27_0
- conda-forge::tk=8.5.19=0
- conda-forge::wheel=0.29.0=py27_0
- conda-forge::xz=5.2.2=0
- conda-forge::zlib=1.2.8=3
- libgfortran=3.0.0=1
- mkl=11.3.3=0
- msgpack-python=0.4.7=py27_0
- numpy=1.11.2=py27_0
- r::libgcc=4.8.5=1
- reportlab=3.3.0=py27_0
- scipy=0.18.1=np111py27_0
- pip:
  - cyvcf==0.1.16
