### ISSUE TITLE
Glossary

### ISSUE THREAD

**Issue by whitneywhitford** [hackseq/2016_project_6#9]
Glossary of terms

**Comment by whitneywhitford** [comment]
Please leave a comment here if you think anything should be included

**Comment by tanyaphung** [comment]
Allele frequency

**Comment by mathbionerd** [comment]
I made a new document for sharing this: 

2016_project_6/Files/Glossary

**Comment by mathbionerd** [comment]
We have a text document for people to add to: [https://github.com/hackseq/2016_project_6/blob/master/Files/Glossary](https://github.com/hackseq/2016_project_6/blob/master/Files/Glossary)
